{
 "title": "utxo-node-prometheus-exporter Copy",
 "time": { "from": "2022-11-04T09:32:47.488Z", "to": "2022-11-04T09:35:17.358Z" },
 "templating": {
  "list": [
   {
    "name": "blockchain",
    "query": {
     "query": "label_values(utxo_node_blocks, blockchain)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Block Creation Rate",
   "type": "graph",
   "description": "Number of blocks created per day using different trailing rates.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum(rate(utxo_node_blocks{blockchain=\"$blockchain\"}[3h])) * 3600 * 24)",
     "legendFormat": "3h"
    },
    {
     "expr": "floor(sum(rate(utxo_node_blocks{blockchain=\"$blockchain\"}[6h])) * 3600 * 24)",
     "legendFormat": "6h"
    },
    {
     "expr": "floor(sum(rate(utxo_node_blocks{blockchain=\"$blockchain\"}[12h])) * 3600 * 24)",
     "legendFormat": "12h"
    },
    {
     "expr": "floor(sum(rate(utxo_node_blocks{blockchain=\"$blockchain\"}[7d])) * 3600 * 24)",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "description": "Difficulty value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(utxo_node_difficulty{blockchain=\"$blockchain\"})",
     "legendFormat": "difficulty"
    }
   ]
  },
  {
   "title": "Network Hash Rate",
   "type": "graph",
   "description": "Estimated network hashes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(utxo_node_hashps{blockchain=\"$blockchain\"})",
     "legendFormat": "120-blocks"
    },
    {
     "expr": "avg(utxo_node_hashps_neg1{blockchain=\"$blockchain\"})",
     "legendFormat": "last-difficulty"
    }
   ]
  },
  {
   "title": "Block value",
   "type": "graph",
   "description": "Value of the block transactions in BTC.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(utxo_node_latest_block_value{blockchain=\"$blockchain\"})",
     "legendFormat": "BTC"
    }
   ]
  },
  {
   "title": "Chain Branches",
   "type": "graph",
   "description": "Number of tips seen in the chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(utxo_node_num_chaintips{blockchain=\"$blockchain\"})",
     "legendFormat": "tips"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "description": "Sent and received traffic rates",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(utxo_node_total_bytes_sent{blockchain=\"$blockchain\"}[5m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "-sum(irate(utxo_node_total_bytes_recv{blockchain=\"$blockchain\"}[10m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Estimated Fee",
   "type": "graph",
   "description": "The estimated smart fee for confirmation of transactions in a given number of blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(utxo_node_est_smart_fee_2{blockchain=\"$blockchain\"})",
     "legendFormat": "2-blocks"
    },
    {
     "expr": "avg(utxo_node_est_smart_fee_20{blockchain=\"$blockchain\"})",
     "legendFormat": "20-blocks"
    },
    {
     "expr": "avg(utxo_node_est_smart_fee_3{blockchain=\"$blockchain\"})",
     "legendFormat": "3-blocks"
    },
    {
     "expr": "avg(utxo_node_est_smart_fee_5{blockchain=\"$blockchain\"})",
     "legendFormat": "5-blocks"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "graph",
   "description": "The Bitcoin protocol and server versions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "protocol version" }
   ],
   "targets": [
    {
     "expr": "avg(utxo_node_protocol_version{blockchain=\"$blockchain\"})",
     "legendFormat": "protocol"
    },
    {
     "expr": "avg(utxo_node_server_version{blockchain=\"$blockchain\"})",
     "legendFormat": "server"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "Number of peers that have been banned and the reason for the ban.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(utxo_node_banned_until{blockchain=\"$blockchain\"}) by (reason)",
     "legendFormat": "ban - {{ reason }}"
    },
    {
     "expr": "sum(utxo_node_peers{blockchain=\"$blockchain\"})",
     "legendFormat": "peers"
    }
   ]
  }
 ]
}